#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 300

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL 92

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX 45

#define SERIAL_NUMBER "aO003/QzJA3D"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 11

#define RGB_MATRIX_STARTUP_SPD 60

